title: "Ahmet Yesevi Türker"
name: "Ahmet Yesevi Türker"
description: "Lead of Data Science & Artificial Intelligence"
url: "https://yeseviturker.github.io"
baseurl: ""

repository: "yeseviturker/yeseviturker.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Ahmet Yesevi Türker"
  avatar: "/assets/ysv_img.png"
  bio: "Lead of Data Science & Artificial Intelligence"
  location: "Istanbul, Turkey"
  email: "yesevi.turker@gmail.com"

search: true

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: single

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

locale: "en-US"
timezone: "Europe/Istanbul"
