title: Ahmet Yesevi Turker
description: Lead of Data Science & Artificial Intelligence
theme: jekyll-theme-minimal
show_downloads: false

author:
  name: Ahmet Yesevi Turker
  email: yesevi.turker@gmail.com

github:
  is_project_page: false
